{
 "title": "Nagasaki",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "settings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select time as \"time\",\n((jsonb_path_query_first(\n\tsettings::jsonb->'strategies', '$.market_making_strategies[*] ? (@.side == \"ASK\")'))\n\t->'calculator_settings'->0->'params'->>'delta_inv_param_min')::DECIMAL\n\tas ask_strategy_delta_inv_param_min,\n((jsonb_path_query_first(\n\tsettings::jsonb->'strategies', '$.market_making_strategies[*] ? (@.side == \"ASK\")'))\n\t->'calculator_settings'->0->'params'->>'delta_inv_param_max')::DECIMAL\n\tas ask_strategy_delta_inv_param_max,\n((jsonb_path_query_first(\n\tsettings::jsonb->'strategies', '$.market_making_strategies[*] ? (@.side == \"BID\")'))\n\t->'calculator_settings'->0->'params'->>'delta_inv_param_min')::DECIMAL\n\tas bid_strategy_delta_inv_param_min,\n((jsonb_path_query_first(\n\tsettings::jsonb->'strategies', '$.market_making_strategies[*] ? (@.side == \"BID\")'))\n\t->'calculator_settings'->0->'params'->>'delta_inv_param_max')::DECIMAL\n\tas bid_strategy_delta_inv_param_max\nfrom settings\nWHERE  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "websocket logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  (message::json->>'price')::DECIMAL as \"ask\"\nFROM websocket_event\nWHERE\n  $__timeFilter(time)\n  and message::json->>'side' = 'ask'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  (message::json->>'price')::DECIMAL as \"bid\"\nFROM websocket_event\nWHERE\n  $__timeFilter(time)\n  and message::json->>'side' = 'bid'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kimsufi cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=~\"user\"}[5m])",
     "legendFormat": "CPU {{cpu}} {{mode}}"
    }
   ]
  },
  {
   "title": "kimsufi free storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\"}",
     "legendFormat": "FREE SPACE"
    },
    { "expression": "$TOTAL-$FREE", "type": "math" }
   ]
  },
  {
   "title": "Moja portmonetka",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"time\",\n  ((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'PLN')::DECIMAL) as \"bitclude PLNs\"\nFROM snapshot\nORDER BY 1 DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  time as \"time\",\n  ((state->'exchange_states'->'deribit'->'account_summary'->>'equity')::DECIMAL *\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"Deribit net worth\"\nFROM snapshot\nORDER BY 1 DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  time as \"time\",\n  ((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"bitclude ETH in PLNs\"\nFROM snapshot\nORDER BY 1 DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "ETH/PLN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    { "expression": "$A * $B", "type": "math" }
   ]
  },
  {
   "title": "ETH/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL as \"ETH/USD\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Net worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'PLN')::DECIMAL) as \"PLNs\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'deribit'->'account_summary'->>'equity')::DECIMAL *\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"Deribit net worth\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n    AVG((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"ETH in PLNs\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    { "expression": "($A + $B + $C)", "type": "math" }
   ]
  },
  {
   "title": "Net worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100*(($A + $B + $C)/7500)-100", "type": "math" }
   ]
  },
  {
   "title": "bitclude vs deribit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL\n  * (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"deribit\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  min_ask_price as \"min ask bitclude\"\nFROM bitclude_ticker_ask\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max_bid_price as \"max bid bitclude\"\nFROM bitclude_ticker_bid\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bitclude net worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'PLN')::DECIMAL) as \"PLNs\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL *\n  (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"ETH in PLNs\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    { "expression": "$A + $C", "type": "math" }
   ]
  },
  {
   "title": "edge pips (1/10 000)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($deribit - $bid) / $deribit * 10000",
     "type": "math"
    },
    {
     "expression": "($ask - $deribit) / $deribit * 10000",
     "type": "math"
    },
    {
     "expression": "($deribit_interpolated - $bid_in_buckets) / $deribit_interpolated * 10000",
     "type": "math"
    },
    {
     "expression": "($ask_in_buckets - $deribit_interpolated) / $deribit_interpolated * 10000",
     "type": "math"
    }
   ]
  },
  {
   "title": "BID/ASK over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price,\n  side\nFROM order_maker\nWHERE\n  side = 'ASK' AND\n  instrument = 'ETH_PLN' AND\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price,\n  side\nFROM order_maker\nWHERE\n  side = 'BID' AND\n  instrument = 'ETH_PLN' AND\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  min_ask_price \"bitclude min ask\"\nFROM bitclude_ticker_ask\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max_bid_price as \"bitclude max bid\"\nFROM bitclude_ticker_bid\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_close AS \"time\",\n  price as \"he sold (ask was filled)\"\nFROM my_trades\nWHERE\n  $__timeFilter(time_close)\n  and type = 'ask'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_close AS \"time\",\n  price as \"he bought (bid was filled)\"\nFROM my_trades\nWHERE\n  $__timeFilter(time_close)\n  and type = 'bid'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'deribit'->'mark_price'->>'ETH')::DECIMAL\n  * (state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"deribit\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Grand total delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'bitclude'->'exchange_balance'->'total'->>'ETH')::DECIMAL) as \"Bitclude ETH\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n    AVG((state->'exchange_states'->'deribit'->'account_summary'->>'margin_balance')::DECIMAL +\n    (state->'exchange_states'->'deribit'->'account_summary'->>'delta_total')::DECIMAL) as \"Deribit delta\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "USD/PLN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  AVG((state->'exchange_states'->'yahoo_finance'->'mark_price'->>'USD/PLN')::DECIMAL) as \"USD/PLN\"\nFROM snapshot\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{container_name=\"nagasaki_nagasaki_1\"} |= ``"
    }
   ]
  }
 ]
}