market_making_instrument: ETH_PLN
hedging_instrument: ETH_PERPETUAL
strategies:
  market_making_strategies:
    - side: ASK
      instrument: ETH_PLN
      symbol: ETH/PLN
      calculator_settings:
        - calculator_type: delta
          params:
            delta_inv_param_min: 0.5
            delta_inv_param_max: 0.5
    - side: BID
      instrument: ETH_PLN
      symbol: ETH/PLN
      calculator_settings:
        - calculator_type: delta
          params:
            delta_inv_param_min: 0.5
            delta_inv_param_max: 0.5
  hedging_strategies:
    - instrument: ETH_PERPETUAL
      symbol: "ETH/USD:ETH"
      grand_total_delta_max: 0.1
      grand_total_delta_min: -0.1