market_making_instrument: BTC_PLN
hedging_instrument: BTC_PERPETUAL
strategies:
  market_making_strategies:
    - side: ASK
      instrument: BTC_PLN
      calculator_settings:
        - calculator_type: delta
          params:
            delta_1: 0.1
            delta_2: 0.2
    - side: BID
      instrument: BTC_PLN
      calculator_settings:
        - calculator_type: delta
          params:
            delta_1: 0.1
            delta_2: 0.2
  hedging_strategies:
    - instrument: BTC_PERPETUAL