version: '3.3'
services:
    grafana:
        ports:
            - '3000:3000'
        volumes:
            - "/home/${USER}/grafana:/var/lib/grafana"
        image: grafana/grafana-oss:9.1.1
        user: "1000"