name: deploy

on:
  push:
    tags:
      - '*'


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to kimsufi
        run: |
          echo $PAPAJ
          docker image prune -af
          docker-compose down
          docker-compose up --build -d
