name: deploy

on:
  push:
    tags:
      - '*'


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose --env-file=/home/ubuntu/nagasaki/.env down
      - run: docker-compose --env-file=/home/ubuntu/nagasaki/.env up --build -d 
