name: deploy

on:
  push:
    tags:
      - '*'


jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Deploy to kimsufi
        uses: appleboy/ssh-action@master
        env:
          COMMIT_SHA: ${{ github.sha }}
          DERIBIT_URL_BASE: ${{ secrets.DERIBIT_URL_BASE }}
          DERIBIT_CLIENT_ID: ${{ secrets.DERIBIT_CLIENT_ID }}
          DERIBIT_CLIENT_SECRET: ${{ secrets.DERIBIT_CLIENT_SECRET }}
          BITCLUDE_URL_BASE: ${{ secrets.BITCLUDE_URL_BASE }}
          BITCLUDE_ID: ${{ secrets.BITCLUDE_ID }}
          BITCLUDE_KEY: ${{ secrets.BITCLUDE_KEY }}
          YAHOO_FINANCE_KEY: ${{ secrets.YAHOO_FINANCE_KEY }}

        with:
          host: "51.68.141.165"
          username: ubuntu
          key: ${{ secrets.ID_HIROSHIMA_PROD }}
          envs: COMMIT_SHA,DERIBIT_URL_BASE,DERIBIT_CLIENT_ID,DERIBIT_CLIENT_SECRET,BITCLUDE_URL_BASE,BITCLUDE_ID,BITCLUDE_KEY,YAHOO_FINANCE_KEY
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ok_proton
            docker image prune -af
            cd ~/git/nagasaki
            git pull
            docker-compose up --force-recreate --build -d
