name: deploy

on:
  push:
    tags:
      - '*'


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:

      - name: Deploy to kimsufi
        run: |
          echo papiez
          echo male dzieci