name: Test dat thing

on:
  push:
    branches: [main]


jobs:
  test-dat-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install deps
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest
          